### ISSUE TITLE
RN端没有提供apk版本号检测吗？

### ISSUE THREAD

**Issue by paulLee73051** [zhijiasoft/react-native-android-auto-update#1]
没有提供检测线上apk与本地apk的版本号方法吗？

**Comment by 1uokun** [comment]
有的，请移步到https://github.com/react-native-community/react-native-device-info#getversion

**Comment by paulLee73051** [comment]
@1uokun 不是这个react-native-device-info，是检测线上即将下载的apk版本号，还没有点击下载安装这一步？在这个方法之前RNAndroidAutoUpdate.goToDownload() 先检测版本的号？

**Comment by 1uokun** [comment]
不好意思，下载前就解析apk并获得版本号的操作目前我还没有见过
这个版本号难倒不应该跟随接口返回给你吗？建议谷歌搜索“android更新策略”
