### ISSUE TITLE
打包APK之后闪退，应该是空指针了，有解决办法吗？

### ISSUE THREAD

**Issue by shdjllajksd** [zhijiasoft/react-native-android-auto-update#3]

**Comment by 1uokun** [comment]
可以发下你的crashlog吗

“打包app”指的是什么🤔
安装app后打开闪退是app的问题哦
下载过程中以及下载完成后闪退的问题最新版本已经修复了

**Comment by shdjllajksd** [comment]
> 可以发下你的crashlog吗
> 
> “打包app”指的是什么🤔
> 安装app后打开闪退是app的问题哦
> 下载过程中以及下载完成后闪退的问题最新版本已经修复了

是安装后启动闪退，我把UpdateApp注释掉就好了，开发环境也没有此问题

**Comment by shdjllajksd** [comment]
> 可以发下你的crashlog吗
> 
> “打包app”指的是什么🤔
> 安装app后打开闪退是app的问题哦
> 下载过程中以及下载完成后闪退的问题最新版本已经修复了

已解决 rm -rf node_moudules/   重新npm install 就好了
